version: '3'

services:
  db:
    build:
      context: data/db
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h 127.0.0.1 --password=$$MYSQL_ROOT_PASSWORD --silent'
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - back-net
    environment:
      - MYSQL_DATABASE=busyness
      - MYSQL_ROOT_PASSWORD
    expose:
      - 3306
      - 33060

  updater:
    build:
      context: updater
    environment:
      - API_HOST=api
      - API_PORT=3000
    networks:
      - front-net
    depends_on:
      api:
        condition: service_started

  knitter:
    build:
      context: knitter
    environment:
      - API_HOST=api
      - API_PORT=3000
    networks:
      - front-net
    depends_on:
      api:
        condition: service_started
    volumes:
      - libraries-data:/knitter/static

  server:
    build:
      context: server
    restart: always
    volumes:
      - libraries-data:/knitter/static
    ports:
      - 8080:8080

  api:
    build:
      context: data/api
    environment:
      - MYSQL_DATABASE=busyness
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_PORT=3306
      - MYSQL_HOST=db
      - API_PORT=3000
    networks:
      - back-net
      - front-net
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 3000

volumes:
  db-data:
  libraries-data:


networks:
  back-net:
  front-net:
